<?php

namespace Database\Seeders\test;

use App\Models\Elog\Lamination;
use Illuminate\Database\Seeder;

class TestLaminationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        Lamination::create([
                'machine_id' => 'Ламинатор 1',
                'work_date' => '2025-01-01',
                'work_shift' => 1,
                'master_id' => 'Поцко С.С.',
                'operator1_id' => 'Иванова М.Л.',
                'operator2_id' => 'Бойцова М.В.',
                'operator3_id' => null,
                'student_id' => null,
                'helper_id' => null,
                'tkn' => '12345a',
                'work_plan' => 100.00,
                'work_start' => '2025-01-01 08:00:00',
                'work_finish' => '2025-01-01 16:00:00',
                'work_fact' => 95.00,
                'customer' => 'Тестовый заказчик',
                'print_title' => 'Тестовый заказ',
                'circulation' => 500.00,
                'mat1_id' => 'BOPP',
                'mat2_id' => 'BOPP: матовый',
                'mat3_id' => 'CPP',
                'width1' => 210.00,
                'width2' => 11.2,
                'width3' => 32.3,
                'thickness1' => 10.00,
                'thickness2' => 4.4,
                'thickness3' => 5.43,
                'mat1count_plan' => 100.00,
                'mat2count_plan' => null,
                'mat3count_plan' => null,
                'mat1count' => 95.00,
                'mat2count' => null,
                'mat3count' => null,
                'workout_mass' => 10.00,
                'workout_length' => 200.00,
                'workout_m2' => 400.00,
                'otk_mass' => 5.00,
                'waste_plan' => 10.00,
                'waste_print' => 5.00,
                'waste_lam' => 5.00,
                'waste_sum' => 15.00,
                'prepare' => null,
                'prepare_shirt' => null,
                'flushing' => null,
                'tech_clean' => null,
                'change_glue' => null,
                'electro' => null,
                'mechanical' => null,
                'tech_service' => null,
                'calibrating' => null,
                'no_human' => null,
                'no_work' => null,
                'no_raw' => null,
                'remain_perv' => 22.3,
                'remain_sec' => 12.1,
                'diff_circulation' => 1221,
                'prepare_ok' => 1,
                'notes' => 'Тестовая нормальная смена',
                'is_idle' => 0,
            ]);
        Lamination::create([
                'machine_id' => 'Ламинатор 1',
                'work_date' => '2025-01-02',
                'work_shift' => 2,
                'master_id' => 'Поцко С.С.',
                'operator1_id' => null,
                'operator2_id' => null,
                'operator3_id' => null,
                'student_id' => null,
                'helper_id' => null,
                'tkn' => null,
                'work_plan' => null,
                'work_start' => null,
                'work_finish' => null,
                'work_fact' => null,
                'customer' => null,
                'print_title' => null,
                'circulation' => null,
                'mat1_id' => null,
                'mat2_id' => null,
                'mat3_id' => null,
                'width1' => null,
                'width2' => null,
                'width3' => null,
                'thickness1' => null,
                'thickness2' => null,
                'thickness3' => null,
                'mat1count_plan' => null,
                'mat2count_plan' => null,
                'mat3count_plan' => null,
                'mat1count' => null,
                'mat2count' => null,
                'mat3count' => null,
                'workout_mass' => null,
                'workout_length' => null,
                'workout_m2' => null,
                'otk_mass' => null,
                'waste_plan' => null,
                'waste_print' => null,
                'waste_lam' => null,
                'waste_sum' => null,
                'prepare' => null,
                'prepare_shirt' => null,
                'flushing' => null,
                'tech_clean' => null,
                'change_glue' => null,
                'electro' => 12,
                'mechanical' => null,
                'tech_service' => null,
                'calibrating' => null,
                'no_human' => null,
                'no_work' => null,
                'no_raw' => null,
                'remain_perv' => null,
                'remain_sec' => null,
                'diff_circulation' => null,
                'prepare_ok' => null,
                'notes' => 'Тестовая смена 12 часов простоя электрика',
                'is_idle' => 1,
        ]);
    }
}
