<?php

namespace Database\Seeders\test;

use App\Models\Elog\Welding;
use Illuminate\Database\Seeder;

class TestWeldingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        Welding::create([
            'machine_id' => 'Интермат-3',
            'work_date' => '2025-01-01',
            'work_shift' => 1,
            'master_id' => 'Поцко С.С.',
            'operator1_id' => 'Иванова М.Л.',
            'operator2_id' => 'Бойцова М.В.',
            'operator3_id' => null,
            'operator4_id' => null,
            'operator5_id' => null,
            'student1_id' => 'Бойцова М.В.',
            'student2_id' => null,
            'acceptor_id' => null,
            'tkn' => '12345a',
            'work_plan' => 100.00,
            'work_start' => '2025-01-01 08:00:00',
            'work_finish' => '2025-01-01 16:00:00',
            'work_fact' => 95.00,
            'customer' => 'Тестовый заказчик',
            'print_title' => 'Тестовый заказ',
            'circulation' => 500.00,
            'product_type' => 1,
            'mat1_id' => 1,
            'mat2_id' => null,
            'mat3_id' => null,
            'product_width' => 210.00,
            'thickness1' => 10.00,
            'thickness2' => null,
            'thickness3' => null,
            'bottom' => 15.00,
            'length' => 200.00,
            'count_plan' => 100.00,
            'count' => 95.00,
            'bottom_type' => 1,
            'is_pocket' => 0,
            'is_handle' => 0,
            'is_edge' => 0,
            'is_perforation' => 0,
            'is_ziplock' => 0,
            'workout_count' => 10.00,
            'workout_otk' => 5.00,
            'waste_plan' => 10.00,
            'waste_print' => 5.00,
            'waste_edge' => 5.00,
            'waste_welding' => 5.00,
            'waste_sum' => 15.00,
            'box_size_id' => null,
            'electro' => null,
            'mechanical' => null,
            'speed' => null,
            'reconfig' => null,
            'calibrating' => null,
            'change_teflon' => null,
            'tech_service' => null,
            'no_human' => null,
            'no_work' => null,
            'no_raw' => null,
            'diff_circulation' => 1221,
            'prepare_ok' => null,
            'notes' => 'Тестовая нормальная смена',
            'is_idle' => 0,
        ]);

        Welding::create([
            'machine_id' => 'Интермат-4',
            'work_date' => '2025-01-02',
            'work_shift' => 2,
            'master_id' => 'Поцко С.С.',
            'operator1_id' => null,
            'operator2_id' => null,
            'operator3_id' => null,
            'operator4_id' => null,
            'operator5_id' => null,
            'student1_id' => null,
            'student2_id' => null,
            'acceptor_id' => null,
            'tkn' => null,
            'work_plan' => null,
            'work_start' => null,
            'work_finish' => null,
            'work_fact' => null,
            'customer' => null,
            'print_title' => null,
            'circulation' => null,
            'product_type' => null,
            'mat1_id' => null,
            'mat2_id' => null,
            'mat3_id' => null,
            'product_width' => null,
            'thickness1' => null,
            'thickness2' => null,
            'thickness3' => null,
            'bottom' => null,
            'length' => null,
            'count_plan' => null,
            'count' => null,
            'bottom_type' => null,
            'is_pocket' => null,
            'is_handle' => null,
            'is_edge' => null,
            'is_perforation' => null,
            'is_ziplock' => null,
            'workout_count' => null,
            'workout_otk' => null,
            'waste_plan' => null,
            'waste_print' => null,
            'waste_edge' => null,
            'waste_welding' => null,
            'waste_sum' => null,
            'box_size_id' => null,
            'electro' => 12,
            'mechanical' => null,
            'speed' => null,
            'reconfig' => null,
            'calibrating' => null,
            'change_teflon' => null,
            'tech_service' => null,
            'no_human' => null,
            'no_work' => null,
            'no_raw' => null,
            'diff_circulation' => null,
            'prepare_ok' => null,
            'notes' => 'Тестовая смена 12 часов простоя электрика',
            'is_idle' => 1,
        ]);
    }
}
