<?php

namespace Database\Seeders\test;

use App\Models\Elog\Extrusion;
use Illuminate\Database\Seeder;

class TestExtrusionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        Extrusion::create([
                'machine_id' => 'Экструдер-20',
                'work_date' => '2025-01-01',
                'work_shift' => 1,
                'master_id' => 'Поцко С.С.',
                'machinist1_id' => 'Иванова М.Л.',
                'machinist2_id' => 'Бойцова М.В.',
                'machinist3_id' => null,
                'student_id' => null,
                'tkn' => '12345a',
                'recipe_number' => 12345,
                'part_number' => 'PN12345',
                'work_plan' => 100.00,
                'work_start' => '2025-01-01 08:00:00',
                'work_finish' => '2025-01-01 16:00:00',
                'work_fact' => 95.00,
                'customer' => 'Тестовый заказчик',
                'print_title' => 'Тестовый заказ',
                'circulation_kg' => 500.00,
                'circulation_length' => 1000.00,
                'product_type' => 1,
                'width' => 210.00,
                'thickness' => 10.00,
                'activation_pole' => 15.00,
                'edge' => 10.00,
                'streams' => 2.00,
                'roll_mass' => 10.00,
                'roll_length' => 200.00,
                'roll_diameter' => 100.00,
                'workout_mass' => 10.00,
                'workout_otk' => 5.00,
                'workout_length' => 200.00,
                'workout_m2' => 400.00,
                'waste_plan_roll' => 10.00,
                'waste_roll' => 5.00,
                'waste_plan_edge' => 5.00,
                'waste_edge' => 5.00,
                'waste_plan_ingets' => 5.00,
                'waste_ingets' => 5.00,
                'waste_slice' => 5.00,
                'waste_trans' => 5.00,
                'waste_sum' => 15.00,
                'electro' => null,
                'mechanical' => null,
                'electronics' => null,
                'tech_service' => null,
                'change_net' => null,
                'change_raw' => null,
                'change_order' => null,
                'clean_machine' => null,
                'no_human' => null,
                'no_work' => null,
                'no_raw' => null,
                'prepare_hours' => null,
                'diff_circulation' => 1221,
                'prepare_ok' => 1,
                'notes' => 'Тестовая нормальная смена',
                'is_idle' => 0,
            ]);

        Extrusion::create([
                'machine_id' => 'Интермат-3',
                'work_date' => '2025-01-02',
                'work_shift' => 2,
                'master_id' => 'Поцко С.С.',
                'machinist1_id' => null,
                'machinist2_id' => null,
                'machinist3_id' => null,
                'student_id' => null,
                'tkn' => null,
                'recipe_number' => null,
                'part_number' => null,
                'work_plan' => null,
                'work_start' => null,
                'work_finish' => null,
                'work_fact' => null,
                'customer' => null,
                'print_title' => null,
                'circulation_kg' => null,
                'circulation_length' => null,
                'product_type' => null,
                'width' => null,
                'thickness' => null,
                'activation_pole' => null,
                'edge' => null,
                'streams' => null,
                'roll_mass' => null,
                'roll_length' => null,
                'roll_diameter' => null,
                'workout_mass' => null,
                'workout_otk' => null,
                'workout_length' => null,
                'workout_m2' => null,
                'waste_plan_roll' => null,
                'waste_roll' => null,
                'waste_plan_edge' => null,
                'waste_edge' => null,
                'waste_plan_ingets' => null,
                'waste_ingets' => null,
                'waste_slice' => null,
                'waste_trans' => null,
                'waste_sum' => null,
                'electro' => 12,
                'mechanical' => null,
                'electronics' => null,
                'tech_service' => null,
                'change_net' => null,
                'change_raw' => null,
                'change_order' => null,
                'clean_machine' => null,
                'no_human' => null,
                'no_work' => null,
                'no_raw' => null,
                'prepare_hours' => null,
                'diff_circulation' => null,
                'prepare_ok' => null,
                'notes' => 'Тестовая смена 12 часов простоя электрика',
                'is_idle' => 1,
        ]);
    }
}
