<?php

namespace Database\Seeders\test;

use App\Models\Elog\Printing;
use Illuminate\Database\Seeder;

class TestPrintingSeeder extends Seeder
{
    public function run(): void

    {
        Printing::create([
                'machine_id' => 'Allstein',
                'work_date' => '2025-01-01',
                'work_shift' => 1,
                'master_id' => 'Поцко С.С.',
                'operator1_id' => 'Иванова М.Л.',
                'operator2_id' => 'Бойцова М.В.',
                'operator3_id' => null,
                'operator_helper' => null,
                'tkn' => '12345a',
                'work_plan' => 100.00,
                'work_start' => '2025-01-01 08:00:00',
                'work_finish' => '2025-01-01 16:00:00',
                'work_fact' => 95.00,
                'customer' => 'Тестовый заказчик',
                'print_title' => 'Тестовый заказ',
                'circulation' => 500.00,
                'mat1_id' => 'Фольга',
                'mat1count_plan' => 100.00,
                'mat1count' => 95.00,
                'width1' => 210.00,
                'thickness1' => 10.00,
                'colors' => 4,
                'workout_mass' => 10.00,
                'workout_length' => 200.00,
                'workout_m2' => 400.00,
                'otk_mass' => 5.00,
                'waste_plan' => 10.00,
                'waste_print' => 5.00,
                'waste_raw' => 5.00,
                'waste_sum' => 15.00,
                'prepare_mass' => 10.00,
                'prepare_hours' => 2.00,
                'correction_PN' => null,
                'correction_CMYK' => null,
                'electro' => null,
                'mechanical' => null,
                'aniloks' => null,
                'clean_machine' => null,
                'form_glue' => null,
                'rakel' => null,
                'clean_dry' => null,
                'clean_val' => null,
                'speed' => null,
                'no_human' => null,
                'no_work' => null,
                'no_raw' => null,
                'diff_circulation' => 1221,
                'notes' => 'Тестовая нормальная смена',
                'is_idle' => 0,
            ]);

             Printing::create([
                'machine_id' => 'Allstein',
                'work_date' => '2025-01-02',
                'work_shift' => 2,
                'master_id' => 'Поцко С.С.',
                'operator1_id' => null,
                'operator2_id' => null,
                'operator3_id' => null,
                'operator_helper' => null,
                'tkn' =>  null,
                'work_plan' => null,
                'work_start' =>  null,
                'work_finish' =>  null,
                'work_fact' =>  null,
                'customer' =>  null,
                'print_title' =>  null,
                'circulation' =>  null,
                'mat1_id' =>  null,
                'mat1count_plan' =>  null,
                'mat1count' => null,
                'width1' => null,
                'thickness1' => null,
                'colors' =>  null,
                'workout_mass' =>  null,
                'workout_length' =>  null,
                'workout_m2' =>  null,
                'otk_mass' =>  null,
                'waste_plan' =>  null,
                'waste_print' =>  null,
                'waste_raw' =>  null,
                'waste_sum' => null,
                'prepare_mass' =>  null,
                'prepare_hours' =>  null,
                'correction_PN' =>  null,
                'correction_CMYK' =>  null,
                'electro' =>  12,
                'mechanical' =>  null,
                'aniloks' =>  null,
                'clean_machine' =>  null,
                'form_glue' =>  null,
                'rakel' =>  null,
                'clean_dry' =>  null,
                'clean_val' =>  null,
                'speed' =>  null,
                'no_human' =>  null,
                'no_work' =>  null,
                'no_raw' =>  null,
                'diff_circulation' =>  null,
                'notes' => 'Тестовая смена 12 часов простоя электрика',
                'is_idle' => 1
        ]);
    }
}
